import Head from "next/head";
// import styles from '@/styles/Home.module.css'
import { useRouter } from "next/router";
import { prisma } from "@/server/db/client";
import { useSession, signIn, signOut } from "next-auth/react";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]";
import axios from "axios";
import { useState, useEffect } from "react";

export default function addDetail({ noteArray }) {

  const router = useRouter();
  const { data: session } = useSession();
  const { id } = router.query;

  if(!session){
    return (
      <>
        Not signed in <br />
        <button onClick={() => signIn()}>Sign in</button>
      </>
    );
  }

  const [detail, setDetail] = useState("")
  const [noteDetail, setNoteDetail] = useState(noteArray)
  
  useEffect(()=>{
    setNoteDetail(noteArray)
  },[noteArray])

  const handleSubmit = async (e) => {
    
    e.preventDefault();
    const {data}  = await axios.post(`/api/notes`, {
      detail
    })
    setNoteDetail([...noteDetail, data])
    console.log("this is data",data)
    // setClear()
    router.push('/profile')
}
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Add a new Todo on the List</h1>

        <div>
          <form onSubmit={handleSubmit}>
            <div>
              <label>Add Note</label>
              <input
                type="text"
                value={detail}
                onChange={(e) => setDetail(e.target.value)}
              />
            </div>

            <div>
              <button type="submit">Add into your Todo Lists</button>
            </div>
          </form>
        </div>
        <button onClick={() => router.push("/profile")}>Back to profile</button>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const notes = await prisma.note.findMany({
    orderBy: {
      id: "desc",
    },
    include: {
      user: true,
    },
  });
  console.log("thisisnote",notes);
  const noteList = JSON.parse(JSON.stringify(notes)) || [];
  const noteArray = Object.values(noteList);

  const session = await getServerSession(context.req, context.res, authOptions);

  return {
    props: {
      session,
      noteArray,
    },
  };
}
