import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Make your to-do list</title>
        <meta name="description" content="Generated by Sue" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome!</h1>
        <div className={styles.container}></div>
        <h3>Before you begin, please sign-in first</h3>
        <button className={styles.button} onClick={()=>router.push('/profile')}>Click Here!</button>

      </main>
    </>
  )
}
