import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '@/comp/Nav'
import TodoInput from '@/comp/TodoInput'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <h1>Todo</h1>

          <div className="center">

            <form onSubmit={handleSubmit} className="form">
              <div className="inner-box">
                <label className="label">Todo</label>
                <TodoInput name = "todo"/>
              </div>

              <div className="inner-box">
                <label className="label">Todo</label>
                <TodoInput name="date" type='date' />
              </div>

              <div className="inner-box">
                <label className="label">Todo</label>
                <TodoInput name="time" type='time'/>
              </div>

              <div className="buttonCont">
                <button className="button" type="submit">Add</button>
              </div>

            </form>

            </div>
      </main>
    </>
  )
}
